# Generated by Django 5.1.1 on 2024-10-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('systolic', models.CharField(max_length=200)),
                ('diastolic', models.CharField(max_length=200)),
                ('meanarterialpressure', models.CharField(max_length=200)),
                ('pulserate', models.CharField(max_length=200)),
            ],
        ),
    ]
