# Generated by Django 5.1.1 on 2024-10-16 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Patient ID / Patient Name')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('idcard', models.CharField(max_length=20, verbose_name='KTP')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('blood_type', models.CharField(max_length=2, verbose_name='Blood Type')),
                ('profile_pic', models.ImageField(upload_to='', verbose_name='Profiel Picture')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created At')),
            ],
        ),
    ]
