# Generated by Django 5.1.1 on 2024-10-16 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Doctor Name')),
                ('birthday', models.DateField(blank=True, verbose_name='Birthday')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('idcard', models.CharField(blank=True, max_length=20, verbose_name='KTP')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile Number')),
                ('blood_type', models.CharField(blank=True, max_length=2, verbose_name='Blood Type')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='Doctor Title')),
                ('profile_pic', models.ImageField(blank=True, upload_to='static', verbose_name='Profile Picture')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created At')),
            ],
        ),
    ]
