# Generated by Django 5.1.1 on 2024-10-16 08:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.TextField(verbose_name='Patient Complains')),
                ('indication', models.TextField(verbose_name='Doctor Indications')),
                ('medicine', models.CharField(max_length=500, verbose_name='Medicines')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created At')),
                ('bp', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='bp.bp')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customer.customer')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='SupportingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static', verbose_name='Image')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctor.patient')),
            ],
        ),
    ]
